language: go

sudo: false

go:
  - 1.8
  - 1.9
  - tip

script:
  - ./.travis.gofmt.sh
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
