name: CI

on:
  pull_request:
    branches:
      - main
      - master

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.3'

      - name: Go Format
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go code is not formatted:"
            gofmt -d .
            exit 1
          fi

      - name: Go Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic

      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)

